# Note: don't use this config for your own repositories. Instead, see
# "Version control integration" in README.md.
default_stages: [commit, push]
exclude: ^(fixtures/)
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: pipenv run isort
        types: [python]
        exclude: tests/
      - id: black
        name: black
        language: system
        entry: pipenv run black
        types: [python]
      - id: pylint
        name: pylint
        language: system
        entry: pipenv run pylint
        types: [python]
      - id: flake8
        name: flake8
        language: system
        entry: pipenv run flake8
        types: [python]
      - id: mypy
        name: mypy
        language: system
        entry: pipenv run mypy
        types: [python]
        exclude: tests/
